#!/bin/sh
# Renders the Homebrew formula for a weft release.
#
#   scripts/homebrew-formula.sh VERSION CHECKSUM_DIR > weft.rb
#
# VERSION is the bare semver (0.1.0, no `v`). CHECKSUM_DIR holds the
# `weft-<target>.sha256` files that .github/workflows/release.yml uploads next
# to each `weft-<target>.tar.gz` (sha256sum format: `<hash>  <file>`). The
# `homebrew` job there runs this and pushes the output to
# SoheilSalmani/homebrew-tap as Formula/weft.rb. Asset names are shared with
# release.yml and install.sh.
set -eu

[ $# -eq 2 ] || {
  printf 'usage: %s VERSION CHECKSUM_DIR\n' "$0" >&2
  exit 2
}
version="$1"
dir="$2"

# Homebrew scans the version from the release URL, which only works for plain
# X.Y.Z (a `-rc.1` suffix scans as garbage), so pre-releases get no formula.
case "$version" in
  *[!0-9.]* | *..* | .* | *. | "")
    printf 'error: version must be X.Y.Z, got %s\n' "$version" >&2
    exit 1
    ;;
esac

# sha TARGET: the checksum recorded for weft-TARGET.tar.gz.
sha() {
  file="$dir/weft-$1.sha256"
  [ -f "$file" ] || {
    printf 'error: missing %s\n' "$file" >&2
    exit 1
  }
  hash="$(awk -v asset="weft-$1.tar.gz" '$2 == asset { print $1 }' "$file")"
  case "$hash" in
    "" | *[!0-9a-f]*)
      printf 'error: %s: no sha256 for weft-%s.tar.gz\n' "$file" "$1" >&2
      exit 1
      ;;
  esac
  [ ${#hash} -eq 64 ] || {
    printf 'error: %s: not a sha256: %s\n' "$file" "$hash" >&2
    exit 1
  }
  printf '%s' "$hash"
}

macos_arm="$(sha aarch64-apple-darwin)"
macos_intel="$(sha x86_64-apple-darwin)"
linux_arm="$(sha aarch64-unknown-linux-gnu)"
linux_intel="$(sha x86_64-unknown-linux-gnu)"

cat <<EOF
# Generated by scripts/homebrew-formula.sh in SoheilSalmani/weft on every
# release; do not edit by hand.
class Weft < Formula
  desc "Record-based project scaffolding"
  homepage "https://github.com/SoheilSalmani/weft"
  license any_of: ["MIT", "Apache-2.0"]

  head do
    url "https://github.com/SoheilSalmani/weft.git", branch: "master"
    depends_on "rust" => :build
  end

  on_macos do
    on_arm do
      url "https://github.com/SoheilSalmani/weft/releases/download/v$version/weft-aarch64-apple-darwin.tar.gz"
      sha256 "$macos_arm"
    end
    on_intel do
      url "https://github.com/SoheilSalmani/weft/releases/download/v$version/weft-x86_64-apple-darwin.tar.gz"
      sha256 "$macos_intel"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/SoheilSalmani/weft/releases/download/v$version/weft-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
    on_intel do
      url "https://github.com/SoheilSalmani/weft/releases/download/v$version/weft-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_intel"
    end
  end

  def install
    if build.head?
      system "cargo", "install", *std_cargo_args(path: "crates/weft-cli")
    else
      bin.install "weft"
    end
  end

  test do
    output = shell_output("#{bin}/weft --version")
    assert_match "weft ", output
    assert_match version.to_s, output unless build.head?
  end
end
EOF
